### ISSUE TITLE
Add generics for better chaining of calls

### ISSUE THREAD

**Issue by cevou** [SAP/ui5-typescript#16]
Hi, 

it would be great if for functions like `byId`, `getModel`, etc. a generic parameter would be added.

Example `byId` returns `sap.ui.core.Element`. If this element happens to be a `sap.m.Input` it is currently not possbile to do something like `view.byId("input").setValue("text")`. This will return an error `setValue does not exist on type Element`.

It would be better if I could write `view.byId<sap.m.Input>("input").setValue("text")`.

This should be added for all functions where the implementation is in a base class and where different element types are returned.

Thank you!

**Comment by bd82** [comment]
Is this information (generics) available in the API.json files?
e.g: https://raw.githubusercontent.com/SAP/ui5-typescript/master/packages/ts-types/input/sap.ui.core.designtime.api.json

As far as I can see it is not...

The d.ts files are generated from the OpenUI5 API.json files which are in turn generated (mostly) from OpenUI5 JSDocs in the source code.

This means that there are two options:

## Make the d.ts generator smarter
Could we logically identify in which situations the generics need to be added?
For example can we define a heuristic to identify when a generic signature should be used?
Alternatively assuming those generic signatures are only rarely needed could we provide
a whitelist of fully qualified method names for which generics should be added?


## Update the original signatures in the OpenUI5 source code.
we will also need to teach the d.ts generator to "understand & generate those generics.


## My Opinion
I think that in general the original OpenUI5 signatures should be improved rather than
added complexity added to this d.ts generator. This may be the exception to the rule however
if we can define a simple heuristic or if the cases in which this need to be applied is limited and suitable for a whitelist.

What do you think @cevou? 

Also: @codeworrior @petermuessig do you have feedback here?

**Comment by bd82** [comment]
## More thoughts
Should the heuristic be based on the return type of methods?
In that case for which "baseTypes"? only `sap.ui.core.Element`? 

This begs the question: the syntax you demonstrated:
- `view.byId<sap.m.Input>("input").setValue("text")`

Still requires you to specify the full type name explicitly, it is not in any way being inferred...
Won't this be true for any method/function in typeScript that returns some BaseClass (regardless of OpenUI5)?

typescript
```
function foo():BaseClass {}
```

Is this not the case for using _type assertions_ rather than generics?
```typescript
(view.byId("input") as sap.m.Input).setValue("text")`
```

**Comment by cevou** [comment]
In both cases (generics as well as type assertions) you have to provide the full name of the class that's being returned.

By using the type assertion the user is basically telling the typescript compiler: Forget what you think what type it is, I know it better. However, there is no further check if this even makes sense. 

If you are using generics you can be more specific. For the `byId` function you could do something like:
```typescript
class View extends sap.ui.core.Control {
  public byId<T extends sap.ui.core.Element>(id: string): T;
}
```
By doing this you make sure, that only subclasses of `sap.ui.core.Element` can be passed in. So the user is not completely overriding the types used.

**Comment by bd82** [comment]
> By doing this you make sure, that only subclasses of sap.ui.core.Element can be passed in. So the user is not completely overriding the types used.

That is a good point.

> Another point is, that in other libraries I am using I rarely or rather never have to use type assertions. Things like this are usually handled with generics.

Other libraries don't have a processes to generate d.ts signatures from another file format
which adds complexity in this case :smile.

I think the questions to answer are now:
- Can these generic signatures be defined in JSDocs? (I can't access the JSDocs page now, will check later...)
- Should we transform return types of (only) a fixed number of top level common base classes to generic signatures?

**Comment by cevou** [comment]
Referring to https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript#template this should be possible:

```javascript
/**
 * @template {sap.ui.core.Element} T
 * @param {string} sId View local ID of the element
 * @return {T} Element by its ID or <code>undefined</code>
 * @public
 */
View.prototype.byId = function(sId) {
  return sap.ui.getCore().byId(this.createId(sId));
};
```

More documentation for the `template` tag can be found in the closure compiler wiki: https://github.com/google/closure-compiler/wiki/Generic-Types

**Comment by codeworrior** [comment]
That is not enough. Our documentation tool chain would have to understand `@template` as well, including the display in the SDK. 

Currently, this is out of scope, at least for the UI5 teams.

**Comment by bd82** [comment]
> That is not enough. Our documentation tool chain would have to understand @template as well, including the display in the SDK.
Currently, this is out of scope, at least for the UI5 teams.

Than if we want to support this we need to perform this fully in the scope of the d.ts generator
Either by using a whitelist of known base classes or identifying base classes.

Would there be any case where adding the generic signatures would be counter productive?

**Comment by codeworrior** [comment]
I'm still thinking where this could/should be used:

- Generic factory or lookup APIs that might return any type of control / element etc.
  This should only be a handful of APIs that might be whitelisted, e.g. _(sorry for the Java style)_
  - &lt;E extends sap.ui.core.Element> sap.ui.core.Core.prototye.byId: E
  - &lt;E extends sap.ui.core.Element> sap.ui.core.mvc.View.prototype.byId: E
  - &lt;E extends sap.ui.core.Element> sap.ui.core.mvc.Controller.prototype.byId E
  - &lt;M extends sap.ui.model.Model> sap.ui.base.ManagedObject.prototype.getModel: M
  - &lt;E extends sap.ui.core.Element> sap.ui.base.ManagedObject.create E
  - &lt;C extends sap.ui.core.Component> sap.ui.core.Component.create: Promise&lt;C>
  - &lt;C extends sap.ui.core.Control> sap.ui.core.Component.prototype.getRootControl: C
  ...

- Getters for Aggregations 
   This will be a bigger list with many methods. Whether a getter should be modeled with generics IMO depends on how likely subclasses of its aggregation type are. Obviously, for the base classes `sap.ui.core.Element` and `sap.ui.core.Control`, this always makes sense. For any other abstract type and for interface types, the same applies. But there might be more cases, e.g. the `Shape` base class for shapes in the Gantt chart - oh, it's also abstract. I'm lacking a good example for a non-abstract base class, but I'm sure there are some.
   Alternatively, we always could add generics to getters, but I have not enough experience with generics in TypeScript to judge side effects /draw backs. If it works like generics in Java, the only drawback that I can imagine is additional writing overhead when you don't care about the type.

- Event objects
    For event objects, generics also might be helpful, but I'm not sure how this could look like. 
    Would the listener method define an `event` parameter with a template type? `getParameters()` then could be a generic method with the corresponding return type.
    - &lt;O extends Object> sap.ui.base.Event.prototype.getParameters: O

- Services
    AFAIK, there's no common interface for services. So what could be the type for the template parameter?
    - &lt;S extends ?> sap.ui.core.Component.prototype.getService: S

...

**Comment by codeworrior** [comment]
BTW: if we would find a way to hide the @template information from the remainder of the tool chain, having it in the source could be supported more easily (up to the first api.json). 

This definitely would make it easier to keep the generics up-to-date.

Maybe something like
```
	{
		"name": "getItems",
		"visibility": "public",
		"templates": {
			"T": "extends sap.ui.core.Item" // or whatever representation would be suitable
		},
		"returnValue": {
			"type": "sap.ui.core.Item[]",
			"typeWithGenerics": "Array<T>" // alternative definition with generics information
		},
		"description": "...
	},
```

Alternatively, we could export the generics in the "type", but re-integrate the parameter information in a post-processing step (which we already have). That way, the type would look the same as before for the SDK (and for the reader of the API reference).

@Nanovsky, @jdichev what do you think?

**Comment by bd82** [comment]
I am closing this and will let @codeworrior continue such investigations in the scope of OpenUI5
as defining the OpenUI5 docs schema is outside the scope of this project.

This project is only responsible for generating valid TypeScript signatures
Not improving the OpenUI5 docs...
