### ISSUE TITLE
`RouteInfo` type is missing in `@sapui5/ts-types-esm` but present in `@types/openui5`

### ISSUE THREAD

**Issue by DetachHead** [SAP/ui5-typescript#301]
sorry if this is the wrong place, not really sure where to raise this

in `@types/openui5` the type is present in the `"sap/ui/core/routing/Router"` module

**Comment by akudev** [comment]
Hi, have you checked [@sapui5/ts-types-esm](https://www.npmjs.com/package/@sapui5/ts-types-esm) as well?  @sapui5/ts-types is known to be of a little lower quality and gets less support, as it is no longer recommended to be used.
@sapui5/ts-types-esm *should* be equal to @types/openui5 as long as versions are equal (of course containing he SAPUI5-only stuff in addition).

**Comment by DetachHead** [comment]
@akudev sorry yeah that's the one I'm using

Btw is there documentation anywhere explaining the difference between `@types/openui5`, `@openui5/ts-types`, `@sapui5/ts-types` and `@sapui5/ts-types-esm`? Seems very odd that there's (at least) 4 different packages that are mostly the same with some seemingly random differences

**Comment by akudev** [comment]
@DetachHead : yeah, I agree that's not so easy to understand and we need to explain the packages better.
But at least they are not random: basically we have two dimension where we need to provide something different:
1. for OpenUI5 we need to provide a reduced package compared to SAPUI5 because it has less controls
2. the old packages supported using global objects like "sap", while in the future we want to encourage using ES modules to load dependencies. For certain stakeholders (WebIDE) we still need to provide the old packages, though.

Those two dimensions are multiplied out, so we get four packages - the ones with `ts-types` in their name. Two for OpenUI5, two for SAPUI5. Two for globals, two for ES modules (those ending with `-esm`). We cannot drop any of them, but I'll see how and where we can document them better and we should also make clearer that the non-esm ones are... less supported.

Then, we also have one more package: `@types/openui5`. The content equals `@openui5/ts-types-esm`, but the *consumption*  is easier because TypeScript automatically finds packages in the `@types` namespace.

**Comment by petermuessig** [comment]
@DetachHead - thanks for providing feedback for the types. As @akudev mentioned, our focus will be the ESM types:

* OpenUI5 type definitions: `@openui5/ts-types-esm` (equal to: `@types/openui5`) 
* SAPUI5 type definitions: `@sapui5/ts-types-esm`

Which types are you using now? `@sapui5/ts-types-esm` or `@sapui5/ts-types`?

**Comment by DetachHead** [comment]
thanks for the clarification! i'm using `@sapui5/ts-types-esm`, i will rename my issues

**Comment by petermuessig** [comment]
Perfect - this helps stops the confusion... 👍

**Comment by akudev** [comment]
@DetachHead I have updated the type definition explanation in https://sap.github.io/ui5-typescript/#what-are-the-typescript-projects-and-releases-provided-by-the-ui5-development-team

**Comment by akudev** [comment]
@DetachHead can you re-check? The `sap.ui.core.d.ts` file is identical for me in `@types/openui5` version 1.97.0 and `@openui5/ts-types-esm` version 1.97.0 and `@sapui5/ts-types-esm` version 1.97.0. Just like it should.

Ensure you have the correct version! "latest" doesn't reliably work right now due to an issue with the `@*ui5/ts-types-esm` versioning on npmjs.

**Comment by DetachHead** [comment]
ah yep it's there in 1.97.0, thanks!

btw is there a separate issue tracking the incorrect `latest` tag? does this happen with every release?

**Comment by akudev** [comment]
Wasn't tracked, Peter wanted to take care of it. I opened https://github.com/SAP/ui5-typescript/issues/320 for it.
