### ISSUE TITLE
@ui5\ts-interface-generator - Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by lemaiwo** [SAP/ui5-typescript#322]
Hi,

When I try to use the ts-interface-genrator it results in the following error:

C:\ui5\app\node_modules\@ui5\ts-interface-generator\dist\interfaceGenerationHelper.js:183
        if (lastParameter.type.kind === ts.SyntaxKind.TypeReference) {
                          ^

TypeError: Cannot read property 'type' of undefined
    at C:\ui5\app\node_modules\@ui5\ts-interface-generator\dist\interfaceGenerationHelper.js:183:27
    at Array.forEach (<anonymous>)
    at getSettingsType (C:\ui5\app\node_modules\@ui5\ts-interface-generator\dist\interfaceGenerationHelper.js:176:18)
    at C:\ui5\app\node_modules\@ui5\ts-interface-generator\dist\interfaceGenerationHelper.js:72:54
    at Array.forEach (<anonymous>)
    at C:\ui5\app\node_modules\@ui5\ts-interface-generator\dist\interfaceGenerationHelper.js:62:46
    at Array.forEach (<anonymous>)
    at C:\ui5\app\node_modules\@ui5\ts-interface-generator\dist\interfaceGenerationHelper.js:60:43
    at Array.forEach (<anonymous>)
    at getManagedObjects (C:\ui5\app\node_modules\@ui5\ts-interface-generator\dist\interfaceGenerationHelper.js:56:27)

In my example the renderer of the control is in a separated file. Any idea what is wrong in my control (it is very basic)?

Kr, Wouter

**Comment by akudev** [comment]
Hi Wouter,
this exception corresponds to the following code line in the original code:
https://github.com/SAP/ui5-typescript/blob/af34287a9264d13423da7d7070bbd487178e583d/packages/ts-interface-generator/src/interfaceGenerationHelper.ts#L251

How the control flow gets there is:
* The generator scans all files in your project to find any ManagedObjects inside
* It finds a file with a top-level class declaration where the class inherits from some superclass
* It looks at that superclass (maybe inside your project, maybe in UI5 or other libraries) and searches for its constructors
* For each constructor it looks at the last parameter's type - assuming this is the settings object from which the settings object for YOUR control needs to inherit
* This lastParameter is undefined - maybe because that constructor does not take any parameters

So in your project, there is a class which inherits from a superclass that has a constructor without arguments.

This sounds like a real bug in the generator, as such classes can of course exist. In a ManagedObject/Control descendant, this shouldn't happen as they are supposed to have only constructors with "settings" argument. But the problematic code runs BEFORE it is verified that your class inherits from ManagedObject.
I will change this, make the code more robust around this area, and also add more (optional) logging/tracing, so the actual location of issues ("in which file?") can be more easily found.

If you want to continue trying before I fix the issue, you could look for that class in your code which inherits from something without constructor parameters and comment out that class.

I'm really sorry that you run into one problem after the other, but this is not an official and well-tested product, it's an alpha version of a tool that I hope will help some people and tested only by myself. So I hope you bear with me and continue trying it and reporting issues.

Not in this case, but in general, as mentioned somewhere in the documentation: when something fails, compare your control code structure, your setup etc. with the one in our sample projects. Same structure should work. But also report the issue please, so the generator can be adapted to the variety of realistic scenarios.

Regards
Andreas
