### ISSUE TITLE
`sap.ushell.Container` removed in 1.100?

### ISSUE THREAD

**Issue by DetachHead** [SAP/ui5-typescript#347]
the `sap.ushell.Container` const that was defined in `sap.ushell.d.ts` seems to no longer be present in version 1.100. how come it was removed?

**Comment by codeworrior** [comment]
@aschmalzhaf can you please take a look and comment? Did only the global name disappear and it's possible now to access `sap.ushell.Container` via a module export in UI5 1.100?

**Comment by aschmalzhaf** [comment]
The issue should be fixed with newer UI5 versions (1.102++ should work fine).
Please excuse all inconveniences.

**Comment by akudev** [comment]
Hold on... I don't think so.

It appears as a class at https://ui5.sap.com/1.101.0/#/api/sap.ushell.Container, but loaded from module "sap/ushell/Container".
In 1.99 it used to be a field on the namespace (https://ui5.sap.com/1.99.0/#/api/sap.ushell), which it isn't anymore.

So it's sort of back again after disappearing in 1.100, but not like it used to be.
A question to @DetachHead would be whether it would be acceptable to import it from module "sap/ushell/Container" instead of addressing it as a global - and whether this works at all, giving access to the singleton instance.

**Comment by akudev** [comment]
Now internally tracked as 2280149651 to get it handled.

**Comment by akudev** [comment]
I verified that the following can be written in TypeScript and also works at runtime to the extent expected:

```ts
import Container from "sap/ushell/Container";
const navService = await Container.getServiceAsync("Navigation");
```

("extent expected" means it fails to return a value in a standalone app without FLP, but `getServiceAsync` is properly called on the right object.)

Closing as finally fixed.
