### ISSUE TITLE
Missing type for `sap.m.PluginBase`

### ISSUE THREAD

**Issue by dfenerski** [SAP/ui5-typescript#367]
[Although this class is not yet public](https://github.com/SAP/openui5/issues/3399), we have built custom plugin which uses the `PluginBase.setConfigs()` method. There are no type definitions for it in the npm package. What is recommended in this case? Should a call be made using global signature i.e `sap.m.PluginBase.setConfigs()`, somehow trick the [import converter](https://github.com/r-murphy/babel-plugin-transform-modules-ui5), or something else?

**Comment by akudev** [comment]
@dfenerski Non-public classes/methods are intentionally not in the type definitions: this way one can avoid writing code that can easily break on updates (because private methods/classes can change at any time). 
If you still want to use this class, you could e.g. define a type for it on your side (i.e. create a *.d.ts file defining the class' interface).
