### ISSUE TITLE
QUnit not recognized when using @sapui5/ts-types[-esm]

### ISSUE THREAD

**Issue by sap-sebelao** [SAP/ui5-typescript#408]
**Describe the bug**
I am getting the following error whenever I attempt to use QUnit while using the https://www.npmjs.com/package/@sapui5/ts-types-esm package for types
![image](https://github.com/SAP/ui5-typescript/assets/91870542/446ab79b-75e8-4977-a52b-508447f1ed92)

I have an internal example than I can provide, but this can also be reproduced using https://github.com/SAP-samples/ui5-typescript-helloworld/tree/testing

1) clone https://github.com/SAP-samples/ui5-typescript-helloworld and checkout the branch `testing`
2) package.json : remove `@types/openui5`, replace with `@sapui5/ts-types-esm@1.116.0` or `@sapui5/ts-types@1.116.0` 
3) `tsconfig.json` now needs to be fixed with `"types": ["@sapui5/ts-types-esm"]`
4) open `webapp/test/unit/controller/App.qunit.ts`

Actually happens in many other files where `QUnit` global is used.

**Expected behavior**
QUnit should be recognized the same as when using `@types/openui5`

**Additional context**
As mentioned above, this happens in the `sapui5` type packages, including the `-esm` version, but does not happen at all in the `openui5` one.

Not sure if this is user error, but I did not find this difference mentioned anywhere, so I expected the packages to work similarly in this case. Sorry if I missed a memo somewhere.

**Comment by akudev** [comment]
As soon as you add `"types": ["@sapui5/ts-types-esm"]` to the tsconfig, you make TypeScript ignore any types except for these when calculating the global scope - see https://www.typescriptlang.org/tsconfig#types
This means that `QUnit` is no longer available globally without importing.

One solution is to also add the QUnit types (`"types": ["@sapui5/ts-types-esm", "@types/qunit"]`) like it is e.g. done in [the Easy UI5 template](https://github.com/ui5-community/generator-ui5-ts-app/blob/main/generators/app/templates/tsconfig.json#L12). In samples using the @types/openui5 the entire `types` entry is unneeded, hence also the addition of @types/qunit cannot be demonstrated.

**Comment by akudev** [comment]
Oh, and please use `@sapui5/types` instead of `@sapui5/ts-types-esm` in version 1.113 and higher!

**Comment by akudev** [comment]
The need to change away from "ts-types-esm" will arise exactly when we stop publishing further updates for that package. ;-) Until then, they are identical.

Does your package.json also require the qunit types? The SAPUI5 types already do that - and reference the closest possible version: not all versions are available, so it's not exactly the one coming with the runtime, regardless of whether the SAPUI5 dependency is used or you have overridden it.

**Comment by akudev** [comment]
> I still got errors, which was strange

This might be related to the qunit types being present twice, once in the toplevel `node_modules` folder because you required them, once below the UI5 types (in `.node_modules/@sapui5/types/node_modules/@types/qunit`). Even when your direct dependency is removed, npm does not move the types up to their standard location, hence the tsconfig settings do not allow them being found. Only when you removed the ts-types-tsm, npm did newly add the qunit types right at toplevel.

> Is sinon getting the same treatment by SAPUI5 types?

No, as the UI5 types do not use any sinon APIs (i.e. no UI5 method returns or requires a type from sinon), our types do not declare sinon to be a dependency.
This means you need to declare the sinon types yourself as dependency and in case there are any globals from them, you also need to add these types to the `"types":` list. That's the drawback of using `"types":`, as I have now described in my multiple-times-edited initial reply above, which I now think overs all relevant options.

**Comment by sap-sebelao** [comment]
Thanks for all the very helpful answers!
