### ISSUE TITLE
[ts-interface-generator] Interface for ManagedObject based Class Instances

### ISSUE THREAD

**Issue by BenReim** [SAP/ui5-typescript#430]
The ts-interface generator should consider cases in which not a class, but an instance is exported.

> e.g. `SampleManagedObject.ts`
```typescript
class SampleManagedObject extends ManagedObject {
 ...
 }

export default new SampleManagedObject();
```

**Comment by akudev** [comment]
Actually, this should already work (and does in my tests). 
The ts-interface-generator finds and enriches the class structures. Whether the class or an instance of it is exported, is an independent matter and whatever you export has the correct enriched structure.
Also, the interface generation does happen no matter what exactly is exported.

This means in case your control file exports an instance instead of the class, like: 
```ts
export default new SampleControl();
```
then the user can - as expected - write:
```ts
import SampleControl from "./SampleControl";
SampleControl.destroyTooltip();
```
Please let me know if there is still some gap I missed.
